<script
	setup
	lang="ts"
>
interface FaqItem {
	label: string;
	content: string;
}

const faqItems: FaqItem[] = [
	{
		label: 'Who is this tool for?',
		content: `<ul>
			<li>Developers who are wanting to pivot into writing Custom WordPress Blocks and write Block Themes, but haven't done much work in React</li>
			<li>Developers who have been using ACF Blocks and would like to begin developing more native WordPress components and UIs</li>
			<li>Experienced developers who want a tool for generating boilerplate, and exploring the wide variety of UI components available.</li>
		</ul>`,
	},
	{
		label: 'Will this tool create ready-to-use blocks?',
		content: '<p>This tool is intended to provide a starting point for your blocks so you can either familiarize yourself with the structure and composition of custom blocks, or as a customizable boilerplate generator. While they will work "out of the box", they\'ll be barebones and You\'ll still need to flesh out the functionality and write any styles that are required to meet your design requirements.</p>',
	},
	{
		label: 'Why can\'t I just use an LLM to generate my blocks?',
		content: '<p>You absolutely can, and you <em>eventually</em> likely will...once you know how they work, and what is possible. LLMs have a propensity for sticking to their own established patterns, and don\'t often pick the best components for the job. Use this tool to explore the different UI possibilities.</p><p>Plus, its always better when you understand how things work under the hood, too!</p>',
	},
	{
		label: 'Why should I learn to write custom blocks?',
		content: '<p>With the robust WordPress Component Library, the Block Editor allows for the creation of custom UI experiences that handles just about any type of content or integration. I\'ve personally been able to build some of the most sophisticated sites of my career due to the Block Editor\'s deep customizability. I find I\'m not even reaching for ACF much these days!</p><p>Also, learning how to write blocks (and work with React more) will also segeue into customizing the Block Editor deeper through its various APIs that are available, as well.</p>',
	},
	{
		label: 'How do I use the code generated by this tool in my project?',
		content: '<p>To effectively use the code generated by this tool, you\'ll need to have the ability to compile and register blocks, and how you want to do that (whether through a plugin or directly into your theme) is up to you.</p><p><strong>Here are some resources to help you along:</strong></p><ul><li><a href="https://css-tricks.com/getting-started-with-wordpress-block-development/" target="_blank">Getting Started With WordPress Block Development - CSS Tricks</a></li><li><a href="https://rudrastyh.com/gutenberg/wordpress-scripts.html" target="_blank">How to Use @wordpress/scripts when Creating a Gutenberg Block</a></li><li><a href="https://developer.wordpress.org/block-editor/reference-guides/packages/packages-create-block/" target="_blank">Official Documentation for @wordpress/create-block</a></li></ul>'
	},
]
</script>

<template>
	<div class="mt-3">
		<UAccordion
			:items="faqItems"
			variant="soft"
			class="w-full"
			:ui="{
				root: 'border-1 border-monokai-blue/20 p-5 pt-0 rounded-md w-full',
				label: 'text-lg text-white hover:text-monokai-yellow group-data-[state=open]:text-monokai-yellow',
				trigger: 'cursor-pointer',
				body: 'leading-[1.8em] [&_a]:text-monokai-blue [&_a]:hover:text-white [&_ul]:list-disc [&_ul]:pl-[25px] [&_ul]:mt-1 [&_li]:mb-3 [&_li]:text-[16px] [&_p]:text-[16px]',
				trailingIcon: 'text-monokai-blue'
			}"
		>
			<template #body="{ item }">
				<!-- eslint-disable-next-line vue/no-v-html, non-dynamic content -->
				<div v-html="item.content" />
			</template>
		</UAccordion>
	</div>
</template>
