<script
	setup
	lang="ts"
>
import type { TabsItem } from '@nuxt/ui';
definePageMeta({ middleware: ['require-components'] })
useSeoMeta({ title: 'Generate — WP Block Composer' });
const blockConfigStore = useBlockConfigStore()
const blockFileStore = useBlockFileStore()
const { blockType } = storeToRefs(blockConfigStore);

const { generatedBlockJson, generatedIndexJs, generatedEditJs, generatedSaveJs } = storeToRefs(blockFileStore);

const fileIcons = computed(() => ({
  json: generatedBlockJson.value ? 'i-lucide-circle-check' : 'i-lucide-file',
  index: generatedIndexJs.value ? 'i-lucide-circle-check' : 'i-lucide-file',
  edit: generatedEditJs.value ? 'i-lucide-circle-check' : 'i-lucide-file',
  save: generatedSaveJs.value ? 'i-lucide-circle-check' : 'i-lucide-file'
}));

const items = computed<TabsItem[]>(() => [
	{
		label: 'block.json',
		icon: fileIcons.value.json,
		slot: 'json' as const
	},
	{
		label: 'index.js',
		icon: fileIcons.value.index,
		slot: 'index' as const
	},
	{
		label: 'edit.js',
		icon: fileIcons.value.edit,
		slot: 'edit' as const
	},
	{
		label: blockType.value === 'dynamic' ? 'render.php' : 'save.js',
		icon: fileIcons.value.save,
		slot: 'save' as const
	},
]);

</script>

<template>
	<div>
		<h2 class="text-2xl font-semibold mb-2">
			Step 3: Generate Files
		</h2>
		<p class="text-monokai-gutter mb-1">
			Review your block configuration and generate the block files.
		</p>
		<UTabs
			:items="items"
			:ui="{
				list: 'my-8 bg-monokai-blue/10',
				leadingIcon: 'transition-all',
				label: 'transition-all'
			}"
			class="w-full"
		>
			<template #json>
				<GenerateJSON />
			</template>
			<template #index>
				<GenerateIndexJS />
			</template>
			<template #edit>
				<GenerateEditJS />
			</template>
			<template #save>
				<GenerateSaveJS />
			</template>
		</UTabs>
		<p class="text-sm text-monokai-gutter/80 my-10 italic border-t border-monokai-line pt-5">
			<strong>Note:</strong> the <code>block.json</code> and <code>index.js</code> are generated deterministically. Due to the the variability of requirements and handlers for each component, <code>edit.js</code> and <code>save.js / render.php</code> are generated by an LLM based on the block and component configurations.
		</p>

	</div>
</template>
